services:
  - type: web
    name: springboot-backend
    runtime: java  # ★ 핵심: 반드시 java로 명시
    javaVersion: 17
    buildCommand: >-
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk &&
      ./gradlew bootJar -Dorg.gradle.java.home=$JAVA_HOME
    startCommand: java -jar build/libs/*.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:mysql://localhost:3306/yuncheong
      - key: SPRING_DATASOURCE_USERNAME
        value: root
      - key: SPRING_DATASOURCE_USERNAME
        value: 1234
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: UPLOAD_DIR
        value: uploads/
      - key: JWT_SECRET
        value: bXlTdXBlclNlY3VyZUtleUZvckhTNTEyQWxnb3JpdGhtV2l0aFN1ZmZpY2llbnRCaXRzTGVuZ3RoMTIzNDU2Nzg5MA==