services:
  - type: web
    name: yun-backend
    env: docker
    repo: https://github.com/yuncheong333/yun-portfolio
    branch: prod
    rootDir: backend
    envVars:
      SPRING_PROFILES_ACTIVE : prod
      PORT: 8080
      DB_PASSWORD: qrwe1423qrwe
      JWT_SECRET: bXlTdXBlclNlY3VyZUtleUZvckhTNTEyQWxnb3JpdGhtV2l0aFN1ZmZpY2llbnRCaXRzTGVuZ3RoMTIzNDU2Nzg5MA==
